---
title: "lab02"
author: "Hanmaro Song"
date: "January 31, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

rdata <- "https://github.com/ucb-stat133/stat133-fall-2017/raw/master/data/nba2017-salary-points.RData"
download.file(url = rdata, destfile = 'nba2017-salary-points.RData')
load('nba2017-salary-points.RData')

# Use length(), head(), tail(), and summary() to start exploring the content of the loaded objects.
length(player)
head(points)
tail(salary)
summary(team)
```

```{r}
# Do all the objects have the same length? Answer: Yes
length(player)
length(points)
length(points1)
length(points2)
length(points3)
length(position)
length(salary)
length(team)
```



```{r}
# Are there missing values, i.e. NA, in any of the objects? Answer: No
any(is.na(player), is.na(points), is.na(points1), is.na(points2), is.na(points3), is.na(position), is.na(salary), is.na(team))
```



```{r}
# Find out what is the class of each of the objects player, team, etc.
class(player)
class(points)
class(points1)
class(points2)
class(points3)
class(position)
class(salary)
class(team)
```
```{r}
#How do you know if any of the loaded objects is a vector?
#Use is.vector() function with each var.

#How do you know that a given vector is of a certain data type?
#Use typeof() with each vector.
```

```{r}




# players in position Center, of Warriors (GSW)
player[position == "C"]

#players of both GSW (warriors) and LAL (lakers)
player[team=="LAL" | team=="GSW"]

#players in positions Shooting Guard and Point Guards, of Lakers (LAL)
player[team=="LAL" & position =="SG" | team=="LAL" & position =="PG"]

#subset Small Forwards of GSW and LAL
temp <-  c(player[position=="SF" & team=="GSW" | position=="SF" & team=="LAL"])
temp

#name of the player with largest salary
player[which.max(salary)]

#name of the player with smallest salary
player[which.min(salary)]

#name of the player with largest number of scored points
player[which.max(points)]

#salary of the player with largest number of points
salary[player == player[which.max(points)]]

#largest salary of all Centers
max(salary[position=="C"])
#team of the player with the largest number of scored points

team[player == player[which.max(points)]]

#name of the player with the largest number of 3-pointers
player[which.max(points3)]

warriors_player = player[team=="GSW"]
warriors_salary = salary[team=="GSW"]
warriors_points = points[team=="GSW"]

# original scal plot
plot(warriors_points, warriors_salary)
text(warriors_points, warriors_salary, labels=abbreviate(warriors_player))

logPoints = log(warriors_points)
logSalary = log(warriors_salary)
# log-trasnformed plot
plot(logPoints, logSalary)
text(logPoints, logSalary, labels=abbreviate(warriors_player))
#create a scatterplot of points and salary for the Warriors (GSW), displaying the names of the players. Generate two scatterplots, one with raw values (original scale, and another plot with log-transformations).

```

-----------------------------------------


